### ISSUE TITLE
开发运行问题

### ISSUE THREAD

**Issue by ChaoShui6626** [jumpserver/lina#104]
部署好jumpserver后端之后  
使用 yarn 命令安装依赖，无异常  
使用 yarn serve命令运行  
登录(登录和登出似乎是后端实现？) 之后跳转 /ui/#/  
然后白屏  
![image](https://user-images.githubusercontent.com/29295507/85009935-cdd6c480-b191-11ea-9b62-9e4143e9bc36.png)
![image](https://user-images.githubusercontent.com/29295507/85009964-d8915980-b191-11ea-83b2-b830a1084616.png)

**Comment by orangemio** [comment]
拉的哪个分支的代码？ 更新到dev最新版本, 检查下ProxyTable的配置。

**Comment by ChaoShui6626** [comment]
重新拉取dev分支， 问题解决
