### ISSUE TITLE
lina左侧路由名称和右侧上面的名称区分开来

### ISSUE THREAD

**Issue by ibuler** [jumpserver/lina#318]
现在左侧的路由名称，就是右侧上面的title名称，有时左侧为了长度美观，会做取舍，但右侧不应该这样，应该描述更多信息

**Comment by jym503558564** [comment]
之前就支持可对右侧标题重写修改
![image](https://user-images.githubusercontent.com/40739051/96442513-d4f40900-123d-11eb-991a-00c29f25897f.png)

**Comment by ibuler** [comment]
授权那个菜单中

- [ ] 资产授权
- [ ] 远程应用
- [ ] 数据库
- [ ] Kubernetes
