### ISSUE TITLE
创建录像/命令存储时，增加help text

### ISSUE THREAD

**Issue by ibuler** [jumpserver/lina#358]
参考 v1.5 版本，另外 help text 文案格式也要统一，

先是说明，后是举例，如下面所示

登录telnet服务器成功后的提示正则表达式，如: Last\s*login|success|成功

https://douyu.fit2cloud.com/terminal/terminal/replay-storage/create/?type=s3

**Comment by jym503558564** [comment]
https://github.com/jumpserver/lina/pull/362
