### ISSUE TITLE
vue.runtime.esm.js:1888 TypeError: Cannot read property 'split' of undefined

### ISSUE THREAD

**Issue by bingws** [jumpserver/lina#446]
更新到v2.4列表显示有下面的错误：

![image](https://user-images.githubusercontent.com/10806595/96425631-d36f1480-122e-11eb-8938-1b7dc767432b.png)

**Comment by jym503558564** [comment]
开源版本吗？

**Comment by jym503558564** [comment]
@bingws

**Comment by bingws** [comment]
解决了。
