### ISSUE TITLE
v2.4.0版本号都不改啊，能认真点么

### ISSUE THREAD

**Issue by lycclsltt** [jumpserver/lina#449]
v2.4.0端版本号都不改啊，能认真点么

**Comment by orangemio** [comment]
你好 麻烦提供下截图

**Comment by lycclsltt** [comment]
这个版本号是从哪传过来的吗？为啥我用了最新的v2.4.1的jumpserver/lina/luna 代码，升级之后还是显示的是v2.3.2

**Comment by orangemio** [comment]
版本号用CI自动构建进去的

**Comment by lycclsltt** [comment]
那为什么我用最新代码升级之后，显示的还是旧版本2.3.2的代码

**Comment by lycclsltt** [comment]
那为什么我用最新代码升级之后，页面上还是显示的是旧版本2.3.2的代码呢

**Comment by lycclsltt** [comment]
那为什么我用v2.4.1最新代码升级之后，页面显示的还是旧版本v2.3.2呢

**Comment by orangemio** [comment]
不知，我看了下release包，里面是 CI 打包正常的。
